[package]
name = "rust_dualsense"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.1"
usb-ids = "0.2.4"
time = "0.3.15"
rand = "0.8.5"